version: "3.7"

services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:4.17
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - 8081:80
    volumes:
      - ./db/pgadmin4/servers.json:/pgadmin4/servers.json

  db-migration:
    image: db_migration:latest
    env_file:
      - ./db/.env
    environment:
      - DATABASE_DNS=postgres
    depends_on:
      - postgres

  valienta-back:
    image: valienta.dev:0.1
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./api:/usr/src/app
      # - nodemodules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db-migration
